### ISSUE TITLE
ModuleNotFoundError: No module named 'psycopg2'

### ISSUE THREAD

**Issue by bashu** [regulusweb/wagtail-extensions#36]
```python
django_1   | Traceback (most recent call last):
django_1   |   File "djangoapp/manage.py", line 25, in <module>
django_1   |     execute_from_command_line(sys.argv)
django_1   |   File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 371, in execute_from_command_line
django_1   |     utility.execute()
django_1   |   File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 347, in execute
django_1   |     django.setup()
django_1   |   File "/usr/local/lib/python3.6/site-packages/django/__init__.py", line 24, in setup
django_1   |     apps.populate(settings.INSTALLED_APPS)
django_1   |   File "/usr/local/lib/python3.6/site-packages/django/apps/registry.py", line 112, in populate
django_1   |     app_config.import_models()
django_1   |   File "/usr/local/lib/python3.6/site-packages/django/apps/config.py", line 198, in import_models
django_1   |     self.models_module = import_module(models_module_name)
django_1   |   File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
django_1   |     return _bootstrap._gcd_import(name[level:], package, level)
django_1   |   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
django_1   |   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
django_1   |   File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
django_1   |   File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
django_1   |   File "<frozen importlib._bootstrap_external>", line 678, in exec_module
django_1   |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
django_1   |   File "/app/djangoapp/contactpage/models.py", line 4, in <module>
django_1   |     from wagtail_extensions.mixins import ContactMixin
django_1   |   File "/usr/local/lib/python3.6/site-packages/wagtail_extensions/mixins.py", line 12, in <module>
django_1   |     from .models import ContactSubmission
django_1   |   File "/usr/local/lib/python3.6/site-packages/wagtail_extensions/models.py", line 1, in <module>
django_1   |     from django.contrib.postgres.fields import JSONField
django_1   |   File "/usr/local/lib/python3.6/site-packages/django/contrib/postgres/fields/__init__.py", line 1, in <module>
django_1   |     from .array import *  # NOQA
django_1   |   File "/usr/local/lib/python3.6/site-packages/django/contrib/postgres/fields/array.py", line 4, in <module>
django_1   |     from django.contrib.postgres.forms import SimpleArrayField
django_1   |   File "/usr/local/lib/python3.6/site-packages/django/contrib/postgres/forms/__init__.py", line 4, in <module>
django_1   |     from .ranges import *  # NOQA
django_1   |   File "/usr/local/lib/python3.6/site-packages/django/contrib/postgres/forms/ranges.py", line 1, in <module>
django_1   |     from psycopg2.extras import DateRange, DateTimeTZRange, NumericRange
django_1   | ModuleNotFoundError: No module named 'psycopg2'
```

I am using mysql in my project...

**Comment by solarissmoke** [comment]
Sorry, but we require psycopg2 for the purposes we use this package for.

**Comment by bashu** [comment]
@solarissmoke do you really need it? I mean there are other implementations of JSONField
